library (devtools)
use_git ()
use_r ('strsplit1')
load_all ()
(x <- "alfa,bravo,charlie,delta")
#> [1] "alfa,bravo,charlie,delta"
strsplit1(x, split = ",")
#> [1] "alfa"    "bravo"   "charlie" "delta"
check ()
use_mit_license ()
document ()
?strsplit1
check ()
install()
library (kochile)
x <- 'alkjf, djlgha, dhs, dd, gypqt03u'
strsplit1(x, split = ',')
use_testthat ()
use_test ('strsplit1')
test ()
use_package ('stringr')
rename_files ('strsplit1', 'str_split_one')
document ()
load_all ()
use_git ()
use_readme_md ()
build_readme ()
check ()
install ()
